version: '3.8'

services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      restart: always
      ports:
        - "1433:1433"
      environment:
        MSSQL_SA_PASSWORD: "yourStrong(!)Password"
        ACCEPT_EULA: "Y"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
